# Generated by Django 3.1 on 2026-06-02 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='varitation_category',
            new_name='variation_category',
        ),
    ]
